services:
  - type: web
    name: vibeverse-backend
    runtime: docker
    repo: hritikagore711/backend
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://hritikagore711:MoodMusic123@cluster0.qoc2agk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0