services:
  - type: web
    name: vibeverse-backend
    runtime: docker
    repo: hritikagore711/backend
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://hritikagore711:...your_full_link_here...
